language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- "./travis-tool.sh install_deps"
- "./travis-tool.sh install_r devtools microbenchmark knitr"
- "./travis-tool.sh install_r arules pbapply memoise stringr"
- "./travis-tool.sh install_r gbm glmnet party survival Matrix"
- "./travis-tool.sh github_package jimhester/covr hadley/purrr"
- "./travis-tool.sh install_github robertzk/Ramd hadley/testthat"
- "./travis-tool.sh install_github robertzk/testthatsomemore"
- "./travis-tool.sh install_github robertzk/objectdiff"
- "./travis-tool.sh install_github robertzk/stagerunner"
- "./travis-tool.sh install_github robertzk/director"
- "./travis-tool.sh install_github robertzk/statsUtils"
- "./travis-tool.sh install_github robertzk/mungebits"
- "./travis-tool.sh install_github robertzk/tundra"
- "./travis-tool.sh install_github robertzk/syberiaMungebits"
- "./travis-tool.sh install_github robertzk/syberiaStructure"
- "./travis-tool.sh install_github robertzk/syberiaStages"
script: "./travis-tool.sh run_tests"
after_failure:
  - "./travis-tool.sh dump_logs"
after_success:
  - "Rscript -e 'library(covr);coveralls()'"
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
  rooms:
    secure: l+wmlZJjYTD9Gv+oSp+y5IE6UFAwGEbfiUdoIU8VA4AihIsarEu9/h1WfuZLf00qlxktx45BLsecvn5QGX+IHVTXDFxmYyL+pzuTdNYZjc87EutstyJ1Ahdt5IA49A8X+PHAO7v60XIjrUrXPKwx3vxsVmO1RSayo0xAwfnupmk= 
env:
  - global:
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0ecure: l+wmlZJjYTD9Gv+oSp+y5IE6UFAwGEbfiUdoIU8VA4AihIsarEu9/h1WfuZLf00qlxktx45BLsecvn5QGX+IHVTXDFxmYyL+pzuTdNYZjc87EutstyJ1Ahdt5IA49A8X+PHAO7v60XIjrUrXPKwx3vxsVmO1RSayo0xAwfnupmk=
